### ISSUE TITLE
Call to undefined method stdClass::undef()

### ISSUE THREAD

**Issue by jeremieb** [tomschwarz/grav-plugin-password-protection#2] opened 2021-04-03 13:12 UTC
Hi there!

I've this issue when I'm trying to protect a page with Grav v1.7.9 and Admin v1.10.8.

/srv/data/web/vhosts/jeremieberduck.com/htdocs/user/plugins/password-protection/password-protection.php

```
public function onAdminSave(Event $event)
    {
        $page = $event["object"];
        if (!method_exists($page, "header")) {
            return;
        }
 
        $header = $page->header();
        $header->undef("feed.skip"); // this part is highlighted
        if (isset($header->pp_protect) && $header->pp_protect) {
            $header->set("feed.skip", true);
        }
 
        if (isset($header->pp_password) && is_string($header->pp_password) 
                && !empty($header->pp_password)) { 
            $hash = $this->_createHash($header->pp_password);
            $header->set("pp_password_hash", $hash);
            $header->undef("pp_password");
        }
    }
```

### Arguments
"Call to undefined method stdClass::undef()"

This is highlighted by the error message: `$header->undef("feed.skip")`

Do you have any idea?

Thanks! ☺️

**Comment by qw3rtty** [comment] 2021-04-03 14:35
@jeremieb 
Thanks for opening this issue!
I will check it out.

**Comment by qw3rtty** [comment] 2021-04-13 07:00
@jeremieb 
Unfortunately I did not had the time to take a closer look on this issue.
I think I will fix it this week!

Hope this is okay for you.

**Comment by jeremieb** [comment] 2021-04-13 07:41
I started to use the Login official plugin on the page I wanted to protect. No rush, I just wanted to let you know the issue on Grav's last version. Good luck for the debug/fix ! ☺️

**Comment by qw3rtty** [comment] 2021-04-16 08:22
@jeremieb 
On the Grav version you mentioned and on the latest one I did not get the error.

Which Plugins do you use? Do you use the `Admin` plugin?
Do you have the [Feed](https://github.com/getgrav/grav-plugin-feed) plugin installed?

**Comment by jeremieb** [comment] 2021-04-16 11:31
Yes for all. This is the list with the versions:
- Admin Panel  v1.10.10
- AdvancedPageCache  v3.0.2
- DevTools  v1.5.1 (turned off)
- Email  v3.1.2
- Error  v1.7.1
- External Links v1.6.3 (turned off)
- Featherlight  v1.5.0
- Feed  v1.8.0
- Flex Objects  v1.0.7
- Form  v5.0.1
- Highlight  v1.5.0 (turned off)
- Login  v3.4.2
- Markdown Notices  v1.1.0
- Pagination  v1.4.2
- Problems  v2.0.3 (turned off)
- Quick Tray Links  v1.0.1 (turned off)

**Comment by qw3rtty** [comment] 2021-04-28 18:45
@jeremieb 
Thanks for your  update!

I tried to reproduce your error. I installed several versions and the exact versions you mentiond.
But I never got the error. So I can't fix it.

I created this plugin for my own usage and I never had this specific issue. 
I use my plugin since it is in the Grav repository.
So I will close this. Sorry that I could not help you!

**Closed as completed by qw3rtty** 2021-04-28 18:45 UTC
Labels: bug, question

**Comment by jeremieb** [comment] 2021-04-29 07:14
No worries. Thanks for trying. ☺️
